# -*- coding: utf-8 -*-
"""Resume_Reviewer_Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p2BczeGNo6TM4EsdP8MEjkTz-UDWjOJZ

#🔥 ResumeReviewer – AI Resume Feedback Chatbot

**Uses: Python, Transformers, NLP, Keyword Extraction**
"""

!pip install transformers sentencepiece

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import re

"""**1. Load a small lightweight AI model (T5-base)**"""

model_name = "google/flan-t5-small"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

"""**2. Basic Resume Checks (Rule-Based)**"""

def rule_based_feedback(text):
    feedback = []

    # Check for contact details
    if not re.search(r'\d{10}', text):
        feedback.append("• Consider adding a valid phone number.")
    if not re.search(r'@', text):
        feedback.append("• Add a professional email address.")

    # Check for skills section
    if "skill" not in text.lower():
        feedback.append("• Add a dedicated SKILLS section.")

    # Check for measurable achievements
    if not re.search(r'\d+%', text) and not re.search(r'\d+\+?', text):
        feedback.append("• Add numbers/metrics to show achievements (e.g., 'Increased sales by 20%').")

    # Check for summary/profile
    if not ("summary" in text.lower() or "objective" in text.lower()):
        feedback.append("• Include a career summary or objective at the top.")

    return feedback

"""**3. AI-based Feedback Using FLAN-T5**"""

def ai_feedback(text):
    prompt = (
        "Give professional resume feedback for the following resume text. "
        "Be specific and helpful:\n\n" + text
    )

    inputs = tokenizer(prompt, return_tensors="pt", truncation=True)
    outputs = model.generate(**inputs, max_length=250)
    result = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return result

"""**4. Chatbot Function**"""

def resume_reviewer_chatbot(resume_text):
    print("\n🔍 Analyzing Resume...\n")

    # Rule-based suggestions
    rules = rule_based_feedback(resume_text)
    print("📌 Rule-based Suggestions:")
    if len(rules) == 0:
        print("✓ No major structural issues found.")
    else:
        for r in rules:
            print(r)

    # AI-powered suggestions
    print("\n🤖 AI-based Feedback:")
    print(ai_feedback(resume_text))

"""**5. Run Chatbot (You can paste your resume here)**"""

resume_input = """
Experienced Python developer with expertise in ML, Deep Learning,
data cleaning, model building, and analytics. Worked on flight price
prediction and churn analysis projects. Familiar with SQL and APIs.
"""

resume_reviewer_chatbot(resume_input)





